substitutions:
  _SERVICE_NAME: secure-app
  _REGION: us-central1

steps:
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  - name: 'snyk/snyk-cli:npm'
    entrypoint: bash
    args:
      - -c
      - |
        snyk auth $SNYK_TOKEN
        snyk test --severity-threshold=high
    secretEnv: ['SNYK_TOKEN']

  - name: 'gcr.io/cloud-builders/bash'
    args: ['./scripts/compliance-check.sh']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA',
      '--region', '$_REGION',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SNYK_TOKEN/versions/latest
      env: 'SNYK_TOKEN'
