steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  - name: 'gcr.io/cloud-builders/curl'
    args: [
      '-X', 'PUT',
      '-u', 'admin:password',
      '-T', 'target/my-app.jar',
      'http://your-artifactory-url/artifactory/libs-release-local/my-app.jar'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['sonar:sonar', '-Dsonar.projectKey=my-app']
